# ===============================
# DEV PROFILE - PostgreSQL local
# ===============================

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/farmdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Security
app.security.jwt.allow-default-secret=true

# Logs
logging.level.org.springframework.security=DEBUG
logging.level.com.jpsoftware.farmapp=DEBUG